import { ICurvedCarouselInfo } from '@/types';

export const fishes: ICurvedCarouselInfo[] = [
  {
    text: 'fishes.africanCichlids.text',
    latinName: 'Pseudotropheus',
    descrp: 'fishes.africanCichlids.descrp',
    src: '/fishes/African_Cichlids.webp',
  },
  {
    text: 'fishes.albinoRainbowShark.text',
    latinName: 'Epalzeorhynchos Frenatum',
    descrp: 'fishes.albinoRainbowShark.descrp',
    src: '/fishes/Albino_Rainbow_Shark.webp',
  },
  {
    text: 'fishes.albinoTigerShark.text',
    latinName: 'Pangasius Hypopthalmus',
    descrp: 'fishes.albinoTigerShark.descrp',
    src: '/fishes/Albino_Tiger_Shark_Doubt.webp',
  },
  {
    text: 'fishes.alligatorGar.text',
    latinName: 'Atractosteus Spatula',
    descrp: 'fishes.alligatorGar.descrp',
    src: '/fishes/Alligator_Gar.webp',
  },
  {
    text: 'fishes.arapaima.text',
    latinName: 'Pirarucu',
    descrp: 'fishes.arapaima.descrp',
    src: '/fishes/Arapaima_.webp',
  },
  {
    text: 'fishes.arowana.text',
    latinName: 'Scleropages Formosus',
    descrp: 'fishes.arowana.descrp',
    src: '/fishes/Arowana_.webp',
  },
  {
    text: 'fishes.bandedLiporinus.text',
    latinName: 'Leporinus Affinis',
    descrp: 'fishes.bandedLiporinus.descrp',
    src: '/fishes/Banded_Liporinus.webp',
  },
  {
    text: 'fishes.blackGhost.text',
    latinName: 'Apteronotus Albifrons',
    descrp: 'fishes.blackGhost.descrp',
    src: '/fishes/Black_Ghost.webp',
  },
  {
    text: 'fishes.bloodRedParrot.text',
    latinName: 'Crossbreed',
    descrp: 'fishes.bloodRedParrot.descrp',
    src: '/fishes/Blood_Red_Parrot.webp',
  },
  {
    text: 'fishes.dragonEel.text',
    latinName: 'Enchelycore Pardalis',
    descrp: 'fishes.dragonEel.descrp',
    src: '/fishes/Dragon_Eel.webp',
  },
  {
    text: 'fishes.filamentalBarb.text',
    latinName: 'Dawkinsia Filamentosa',
    descrp: 'fishes.filamentalBarb.descrp',
    src: '/fishes/Filamental_Barb.webp',
  },
  {
    text: 'fishes.giantGourami.text',
    latinName: 'Osphronemus Gourami',
    descrp: 'fishes.giantGourami.descrp',
    src: '/fishes/Giant_gourami.webp',
  },
  {
    text: 'fishes.koiCarp.text',
    latinName: 'Cyprinus Carpio',
    descrp: 'fishes.koiCarp.descrp',
    src: '/fishes/Koi_Carp.webp',
  },
  {
    text: 'fishes.milkyKoi.text',
    latinName: 'Cyprinus Rubrofuscus',
    descrp: 'fishes.milkyKoi.descrp',
    src: '/fishes/Milky_Koi.webp',
  },
  {
    text: 'fishes.oscarFish.text',
    latinName: 'Astronotus Ocellatus',
    descrp: 'fishes.oscarFish.descrp',
    src: '/fishes/Oscar_Fish.webp',
  },
  {
    text: 'fishes.rainbowShark.text',
    latinName: 'Epalzeorhynchos Frenatum',
    descrp: 'fishes.rainbowShark.descrp',
    src: '/fishes/Rainbow_Shark.webp',
  },
  {
    text: 'fishes.redBelliedPacu.text',
    latinName: 'Piaractus Brachypomum',
    descrp: 'fishes.redBelliedPacu.descrp',
    src: '/fishes/Red_Bellied_Pacu.webp',
  },
  {
    text: 'fishes.redBelliedPiranha.text',
    latinName: 'Pygocentrus Nattereri',
    descrp: 'fishes.redBelliedPiranha.descrp',
    src: '/fishes/Red_Bellied_Piranha_.webp',
  },
  {
    text: 'fishes.redDevil.text',
    latinName: 'Amphilophus Labiatus',
    descrp: 'fishes.redDevil.descrp',
    src: '/fishes/Red_Devil.webp',
  },
  {
    text: 'fishes.redTailCatfish.text',
    latinName: 'Phractocephalus Hemioliopterus',
    descrp: 'fishes.redTailCatfish.descrp',
    src: '/fishes/Red_Tail_Catfish.webp',
  },
  {
    text: 'fishes.redTailShovelnoseCatfish.text',
    latinName: 'Phractocephalus Hemioliopterus',
    descrp: 'fishes.redTailShovelnoseCatfish.descrp',
    src: '/fishes/Red_Tail_Shovelnose_Catfish.webp',
  },
  {
    text: 'fishes.severum.text',
    latinName: 'Heros Severus',
    descrp: 'fishes.severum.descrp',
    src: '/fishes/Severum.webp',
  },
  {
    text: 'fishes.shortFinEel.text',
    latinName: 'Anguilla Australis',
    descrp: 'fishes.shortFinEel.descrp',
    src: '/fishes/Short_Fin_Eel.webp',
  },
  {
    text: 'fishes.shovelnoseCatfish.text',
    latinName: 'Pseudoplatystoma Fasciatum',
    descrp: 'fishes.shovelnoseCatfish.descrp',
    src: '/fishes/Shovelnose_Catfish.webp',
  },
  {
    text: 'fishes.sunCatfish.text',
    latinName: 'Horabagrus Brachysoma',
    descrp: 'fishes.sunCatfish.descrp',
    src: '/fishes/Sun_Catfish.webp',
  },
  {
    text: 'fishes.tigerBarb.text',
    latinName: 'Barbus Tetrazona',
    descrp: 'fishes.tigerBarb.descrp',
    src: '/fishes/Tiger_Barb.webp',
  },
  {
    text: 'fishes.tigerShark.text',
    latinName: 'Pangasius Hypopthalmus',
    descrp: 'fishes.tigerShark.descrp',
    src: '/fishes/Tiger_Shark.webp',
  },
  {
    text: 'fishes.tilapia.text',
    latinName: 'Oreochromis',
    descrp: 'fishes.tilapia.descrp',
    src: '/fishes/Tilapia.webp',
  },
];
