import {
  IAmenity,
  IExpandGroup,
  IImageCard,
  IImportant,
  ILanguageOption,
  IVideoImage,
  IVideoLink,
} from '@/types';

export const languageOptions: ILanguageOption[] = [
  { name: 'English', code: 'en' },
  { name: 'Marathi', code: 'mr' },
];

export const amenities: IAmenity[] = [
  { name: 'amenities.cafe', icon: '/amenities/food.svg' },
  { name: 'amenities.washroom', icon: '/amenities/washroom.svg' },
  { name: 'amenities.parking', icon: '/amenities/parking.svg' },
  { name: 'amenities.buggyStand', icon: '/amenities/buggy.svg' },
  { name: 'amenities.restaurant', icon: '/amenities/restaurant.svg' },
  { name: 'amenities.waterCoolers', icon: '/amenities/water.svg' },
  { name: 'amenities.feedingRoom', icon: '/amenities/feeding.svg' },
  { name: 'amenities.souvenirShop', icon: '/amenities/gift.svg' },
  { name: 'amenities.restShelters', icon: '/amenities/rest.svg' },
  { name: 'amenities.guides', icon: '/amenities/guide.svg' },
  { name: 'amenities.ticketCounter', icon: '/amenities/ticket.svg' },
  { name: 'amenities.playArea', icon: '/amenities/play.svg' },
  { name: 'amenities.waterFountains', icon: '/amenities/fountain.svg' },
];

export const disabledDates = [3, 10, 17, 24, 31];

export const shopPlayDineItems: IVideoLink[] = [
  { src: '/shop/shop-1.webp' },
  { src: '/shop/shop-2.webp' },
  { src: '/shop/shop-3.webp' },
];

export const bookingGroups: IExpandGroup[] = [
  {
    name: 'bookingGroups.group.name',
    color: '#008080AA',
    text: 'bookingGroups.group.text',
    pdfLink: '/PDF/Group.pdf',
    images: [
      '/expand/group/group.png',
      '/expand/group/group-1.png',
      '/expand/group/group-2.png',
      '/expand/group/group-3.png',
      '/expand/group/group-4.png',
      '/expand/group/group-5.png',
      '/expand/group/group-6.png',
    ],
  },
  {
    name: 'bookingGroups.students.name',
    color: '#FF5E00AA',
    text: 'bookingGroups.students.text',
    pdfLink: '/PDF/Students.pdf',
    images: [
      '/expand/students/students.png',
      '/expand/students/students-1.png',
      '/expand/students/students-2.png',
      '/expand/students/students-3.png',
      '/expand/students/students-4.png',
      '/expand/students/students-5.png',
      '/expand/students/students-6.png',
    ],
  },
  {
    name: 'bookingGroups.seniorCitizens.name',
    color: '#C6C1FFAA',
    text: 'bookingGroups.seniorCitizens.text',
    pdfLink: '/PDF/Senior-Citizens.pdf',
    images: [
      '/expand/senior/senior.png',
      '/expand/senior/senior-1.png',
      '/expand/senior/senior-2.png',
      '/expand/senior/senior-3.png',
      '/expand/senior/senior-4.png',
      '/expand/senior/senior-5.png',
      '/expand/senior/senior-6.png',
    ],
  },
  {
    name: 'bookingGroups.kids.name',
    color: '#FFC000AA',
    text: 'bookingGroups.kids.text',
    pdfLink: '/PDF/Kids.pdf',
    images: [
      '/expand/kids/kids.png',
      '/expand/kids/kids-1.png',
      '/expand/kids/kids-2.png',
      '/expand/kids/kids-3.png',
      '/expand/kids/kids-4.png',
      '/expand/kids/kids-5.png',
      '/expand/kids/kids-6.png',
    ],
  },
  {
    name: 'bookingGroups.influencers.name',
    color: '#DEA193AA',
    text: 'bookingGroups.influencers.text',
    pdfLink: '/PDF/Influencers.pdf',
    images: [
      '/expand/influencers/influencers.png',
      '/expand/influencers/influencers-1.png',
      '/expand/influencers/influencers-2.png',
      '/expand/influencers/influencers-3.png',
      '/expand/influencers/influencers-4.png',
      '/expand/influencers/influencers-5.png',
      '/expand/influencers/influencers-6.png',
    ],
  },
  {
    name: 'bookingGroups.natureEnthusiasts.name',
    color: '#005E03AA',
    text: 'bookingGroups.natureEnthusiasts.text',
    pdfLink: '/PDF/Nature-Enthusiasts.pdf',
    images: [
      '/expand/nature/nature.png',
      '/expand/nature/nature-1.png',
      '/expand/nature/nature-2.png',
      '/expand/nature/nature-3.png',
      '/expand/nature/nature-4.png',
      '/expand/nature/nature-5.png',
      '/expand/nature/nature-6.png',
    ],
  },
];

export const support: IImageCard[] = [
  {
    name: 'supportTitles.career',
    src: '/support/support-1.webp',
    link: '/about#team',
  },
  {
    name: 'supportTitles.guidance',
    src: '/support/support-2.webp',
    link: '/about#team',
  },
  { name: 'supportTitles.services', src: '/support/support-3.webp' },
  {
    name: 'supportTitles.sponsorshipsDonation',
    src: '/support/support-4.webp',
  },
  { name: 'supportTitles.membership', src: '/support/support-5.webp' },
  {
    name: 'supportTitles.updates',
    src: '/support/support-6.webp',
    link: '/#table',
  },
  {
    name: 'supportTitles.specialEvents',
    src: '/support/support-7.webp',
    link: '/#table',
  },
];

export const importants: IImportant[] = [
  {
    icon: '/icons/closed.svg',
    text: 'importants.closed',
    body: 'Tuesday',
  },
  {
    icon: '/icons/alarm.svg',
    text: 'importants.timings',
    body: '10:00 AM - 6:00 PM',
  },
  {
    icon: '/icons/fast-food.svg',
    text: 'importants.restaurant',
    body: '10:00 AM - 11:00 PM',
  },
  {
    icon: '/icons/place.svg',
    text: 'importants.letsMeet',
    body: 'Direction',
  },
];

export const activities: IVideoImage[] = [
  {
    name: 'activities.environmentalAwareness',
    src: '/activities/activity-1.webp',
    video: 'https://www.youtube.com/embed/A0S_TgvHuXM',
  },
  {
    name: 'activities.lifetimeExperiences',
    src: '/activities/activity-2.webp',
    video: 'https://www.youtube.com/embed/HS5ktxvKEKM',
  },
  {
    name: 'activities.relaxingMeditativeActivities',
    src: '/activities/activity-3.webp',
    video: 'https://www.youtube.com/embed/X2-3ElZ5jgQ',
  },
  {
    name: 'activities.communityForum',
    src: '/activities/activity-4.webp',
    video: 'https://www.youtube.com/embed/-zAoqZGn-dU',
  },
  {
    name: 'activities.natureOuting',
    src: '/activities/activity-5.webp',
    video: 'https://www.youtube.com/embed/cDLDitMuxTU',
  },
];

export const learnCards: IImageCard[] = [
  { name: 'learnCards.resourceHub', src: '/learn/learn-1.webp' },
  { name: 'learnCards.learningProgrammes', src: '/learn/learn-2.webp' },
  {
    name: 'learnCards.internshipFellowship',
    src: '/learn/learn-3.webp',
  },
];

export const galleryImages: string[] = [
  '/learn/learn-1.webp',
  '/learn/learn-2.webp',
  '/learn/learn-3.webp',
  '/shop/shop-1.webp',
  '/shop/shop-2.webp',
  '/shop/shop-3.webp',
  '/expand/group/group.png',
  '/expand/group/group-1.png',
  '/expand/group/group-2.png',
  '/expand/group/group-3.png',
  '/expand/group/group-4.png',
  '/expand/group/group-5.png',
  '/expand/group/group-6.png',
  '/expand/students/students.png',
  '/expand/students/students-1.png',
  '/expand/students/students-4.png',
  '/expand/students/students-5.png',
  '/expand/senior/senior.png',
  '/expand/senior/senior-1.png',
  '/expand/senior/senior-2.png',
  '/expand/senior/senior-4.png',
  '/expand/senior/senior-5.png',
  '/expand/kids/kids.png',
  '/expand/kids/kids-1.png',
  '/expand/kids/kids-2.png',
  '/expand/kids/kids-3.png',
  '/expand/kids/kids-4.png',
  '/expand/kids/kids-5.png',
  '/expand/kids/kids-6.png',
  '/expand/influencers/influencers-1.png',
  '/expand/influencers/influencers-2.png',
  '/expand/influencers/influencers-4.png',
  '/expand/influencers/influencers-5.png',
  '/expand/nature/nature.png',
  '/expand/nature/nature-1.png',
  '/expand/nature/nature-2.png',
  '/expand/nature/nature-3.png',
  '/expand/nature/nature-5.png',
  '/expand/nature/nature-6.png',
  '/glimpses/glimpses-1.webp',
  '/glimpses/glimpses-2.webp',
  '/glimpses/glimpses-3.webp',
  '/glimpses/glimpses-4.webp',
  '/glimpses/glimpses-5.webp',
  '/glimpses/glimpses-6.webp',
  '/glimpses/glimpses-7.webp',
  '/glimpses/glimpses-8.webp',
  '/glimpses/glimpses-9.webp',
  '/about/about-1.webp',
  '/about/about-2.webp',
  '/about/about-4.webp',
  '/wide-carousel/wide-carousel-1.webp',
  '/wide-carousel/wide-carousel-2.webp',
  '/wide-carousel/wide-carousel-3.webp',
  '/wide-carousel/wide-carousel-4.webp',
  '/wide-carousel/wide-carousel-5.webp',
  '/wide-carousel/wide-carousel-6.webp',
  '/wide-carousel/wide-carousel-7.webp',
  '/inauguration/1.webp',
  '/inauguration/2.webp',
  '/inauguration/3.webp',
  '/inauguration/4.webp',
  '/inauguration/5.webp',
  '/inauguration/6.webp',
  '/inauguration/7.webp',
  '/inauguration/8.webp',
  '/inauguration/9.webp',
  '/inauguration/10.webp',
  '/inauguration/11.webp',
  '/inauguration/12.webp',
  '/inauguration/13.webp',
  '/inauguration/14.webp',
  '/inauguration/15.webp',
  '/inauguration/16.webp',
  '/inauguration/17.webp',
  '/inauguration/18.webp',
  '/inauguration/19.webp',
  '/inauguration/20.webp',
  '/inauguration/21.webp',
  '/inauguration/22.webp',
  '/inauguration/23.webp',
  '/inauguration/24.webp',
  '/inauguration/25.webp',
  '/inauguration/26.webp',
  '/inauguration/27.webp',
  '/inauguration/28.webp',
  '/inauguration/29.webp',
  '/inauguration/30.webp',
  '/inauguration/31.webp',
  '/inauguration/32.webp',
  '/inauguration/33.webp',
  '/inauguration/34.webp',
  '/inauguration/35.webp',
  '/inauguration/36.webp',
  '/inauguration/37.webp',
  '/inauguration/38.webp',
  '/inauguration/39.webp',
  '/inauguration/40.webp',
  '/inauguration/41.webp',
  '/inauguration/42.webp',
  '/inauguration/43.webp',
  '/inauguration/44.webp',
  '/inauguration/45.webp',
  '/inauguration/46.webp',
  '/inauguration/47.webp',
  '/inauguration/48.webp',
  '/inauguration/49.webp',
  '/inauguration/50.webp',
  '/inauguration/51.webp',
  '/inauguration/52.webp',
  '/inauguration/53.webp',
  '/inauguration/54.webp',
  '/inauguration/55.webp',
  '/inauguration/56.webp',
  '/inauguration/57.webp',
  '/inauguration/58.webp',
  '/inauguration/59.webp',
  '/inauguration/60.webp',
  '/inauguration/61.webp',
  '/inauguration/62.webp',
  '/inauguration/63.webp',
  '/inauguration/64.webp',
  '/inauguration/65.webp',
  '/inauguration/66.webp',
  '/inauguration/67.webp',
  '/inauguration/68.webp',
  '/inauguration/69.webp',
  '/inauguration/70.webp',
];
