import { ILocation } from '@/types';

const restLocations: ILocation[] = [
  {
    name: 'Rest Shelter',
    value: '/amenities/rest.svg',
    color: '#9A0ADD',
    left: 33.25,
    top: 96.75,
    direction: false,
  },
  {
    name: 'Rest Shelters',
    value: '/amenities/rest.svg',
    color: '#9A0ADD',
    left: 25,
    top: 88.25,
    direction: false,
  },
  {
    name: 'Rest Shelters',
    value: '/amenities/rest.svg',
    color: '#9A0ADD',
    left: 40,
    top: 83.5,
    direction: false,
  },
  {
    name: 'Rest Shelters',
    value: '/amenities/rest.svg',
    color: '#9A0ADD',
    left: 21,
    top: 82.5,
    direction: false,
  },
  {
    name: 'Rest Shelters',
    value: '/amenities/rest.svg',
    color: '#9A0ADD',
    left: 70,
    top: 82.5,
    direction: false,
  },
  {
    name: 'Rest Shelters',
    value: '/amenities/rest.svg',
    color: '#9A0ADD',
    left: 26,
    top: 73.5,
    direction: false,
  },
];

const washroomLocations: ILocation[] = [
  {
    name: 'Wash-room',
    value: '/amenities/washroom.svg',
    color: '#0038C5',
    left: 40.75,
    top: 92.5,
    direction: false,
  },
  {
    name: 'Wash-room',
    value: '/amenities/washroom.svg',
    color: '#0038C5',
    left: 56,
    top: 86.5,
    direction: false,
  },
  {
    name: 'Wash-room',
    value: '/amenities/washroom.svg',
    color: '#0038C5',
    left: 20.25,
    top: 77,
    direction: false,
  },
];

const drinkingWater: ILocation[] = [
  {
    name: 'Water Cooler',
    value: '/amenities/water.svg',
    color: '#17A1FA',
    left: 41.75,
    top: 87.25,
    direction: false,
  },
  {
    name: 'Water Cooler',
    value: '/amenities/water.svg',
    color: '#17A1FA',
    left: 71.5,
    top: 78.5,
    direction: false,
  },
  {
    name: 'Water Cooler',
    value: '/amenities/water.svg',
    color: '#17A1FA',
    left: 43,
    top: 72,
    direction: false,
  },
  {
    name: 'Water Cooler',
    value: '/amenities/water.svg',
    color: '#17A1FA',
    left: 23,
    top: 72.25,
    direction: false,
  },
];

const parking: ILocation[] = [
  {
    name: 'Parking',
    value: '/amenities/parking.svg',
    left: 67,
    top: 88,
    color: '#F3BB17',
    direction: false,
  },
  {
    name: 'Parking',
    value: '/amenities/parking.svg',
    left: 57.5,
    top: 83.5,
    color: '#F3BB17',
    direction: false,
  },
];

const buggyStand: ILocation[] = [
  {
    name: 'Buggy Stand',
    value: '/amenities/buggy.svg',
    left: 45,
    top: 67,
    color: '#008804',
    direction: true,
  },
  {
    name: 'Buggy Stand',
    value: '/amenities/buggy.svg',
    left: 58.75,
    top: 79.75,
    color: '#008804',
    direction: false,
  },
];

const numberedLocations: ILocation[] = [
  {
    name: 'Main Entrance Gate',
    value: 1,
    left: 62.25,
    top: 88.25,
    direction: false,
  },
  {
    name: 'Admin Building',
    value: 2,
    left: 50.75,
    top: 70,
    direction: false,
  },
  {
    name: 'Biodiversity Centre',
    value: 3,
    left: 55,
    top: 72.25,
    direction: false,
  },
  {
    name: 'Statue of Nature',
    value: 4,
    left: 46,
    top: 69.5,
    direction: false,
  },
  {
    name: 'Fountain',
    value: 5,
    left: 45,
    top: 74.25,
    direction: false,
  },
  {
    name: 'Rose Garden',
    value: 6,
    left: 48,
    top: 78,
    direction: false,
  },
  {
    name: 'Shrubbery Garden',
    value: 7,
    left: 44,
    top: 82,
    direction: false,
  },
  {
    name: 'Natural History Museum',
    value: 8,
    left: 36.5,
    top: 92,
    direction: false,
  },
  {
    name: 'Butterfly Garden',
    value: 9,
    left: 36,
    top: 85.5,
    direction: false,
  },
  {
    name: 'Science Center',
    value: 10,
    left: 28,
    top: 85.25,
    direction: false,
  },
  {
    name: 'Planetarium',
    value: 11,
    left: 25.5,
    top: 80.25,
    direction: false,
  },
  {
    name: 'Aquarium',
    value: 12,
    left: 26.75,
    top: 75.25,
    direction: false,
  },
  {
    name: 'Science Park',
    value: 13,
    left: 17,
    top: 73,
    direction: false,
  },
  {
    name: 'Bougainville Garden',
    value: 14,
    left: 31,
    top: 69.75,
    direction: false,
  },
  {
    name: 'Evolution Park',
    value: 15,
    left: 66.5,
    top: 82.5,
    direction: false,
  },
  {
    name: 'Mathematics Park',
    value: 16,
    left: 74.5,
    top: 80,
    direction: false,
  },
  {
    name: 'Medicinal Garden',
    value: 17,
    left: 65.5,
    top: 74.25,
    direction: false,
  },
  {
    name: 'Exhibition Center',
    value: 18,
    left: 72.5,
    top: 72,
    direction: false,
  },
  {
    name: 'Glass Houses',
    value: 19,
    left: 74.25,
    top: 68.5,
    direction: false,
  },
  {
    name: 'Maze',
    value: 20,
    left: 80.5,
    top: 70.5,
    direction: false,
  },
  {
    name: 'Conservation Gate',
    value: 21,
    left: 48.5,
    top: 66.75,
    direction: false,
  },
  {
    name: 'Bharat Van',
    value: 22,
    left: 49,
    top: 62,
    direction: false,
  },
  {
    name: 'Ganesh Patri Van',
    value: 23,
    left: 47.5,
    top: 54.25,
    direction: false,
  },
  {
    name: 'Rudraksh Van',
    value: 24,
    left: 52,
    top: 49,
    direction: false,
  },
  {
    name: 'Nakshtra Van',
    value: 25,
    left: 46.25,
    top: 43.75,
    direction: false,
  },
  {
    name: 'Rashi',
    value: 26,
    left: 45.25,
    top: 46.5,
    direction: false,
  },
  {
    name: 'Trimurti Van',
    value: 27,
    left: 41,
    top: 45,
    direction: false,
  },
  {
    name: 'Navgraha Van',
    value: 28,
    left: 38,
    top: 47.5,
    direction: false,
  },
  {
    name: 'Saptarishi Van',
    value: 29,
    left: 48,
    top: 48.5,
    direction: false,
  },
  {
    name: 'Nandan Van',
    value: 30,
    left: 55,
    top: 58.5,
    direction: false,
  },
  {
    name: 'Panchavati Van',
    value: 31,
    left: 58,
    top: 55,
    direction: true,
  },
  {
    name: 'Bamboo Van',
    value: 32,
    left: 63,
    top: 53,
    direction: true,
  },
  {
    name: 'Mati Nalla Bund',
    value: 33,
    left: 65,
    top: 56,
    direction: true,
  },
  {
    name: 'Ramayan Van',
    value: 34,
    left: 75.75,
    top: 53.75,
    direction: false,
  },
  {
    name: 'Palm Garden',
    value: 35,
    left: 53.5,
    top: 38.5,
    direction: false,
  },
  {
    name: 'Open Butterfly Garden',
    value: 36,
    left: 48.5,
    top: 36.25,
    direction: false,
  },
  {
    name: 'Kidney Shaped Water',
    value: 37,
    left: 43.5,
    top: 37.5,
    direction: false,
  },
  {
    name: 'BRTC Bamboo Setum',
    value: 38,
    left: 33,
    top: 14,
    direction: false,
  },
  {
    name: 'Central Water Body',
    value: 39,
    left: 64,
    top: 30,
    direction: false,
  },
  {
    name: 'Lotus Garden',
    value: 40,
    left: 73.25,
    top: 25.75,
    direction: false,
  },
  {
    name: 'Dumbbell Shaped Water',
    value: 41,
    left: 78.5,
    top: 27,
    direction: false,
  },
  {
    name: 'Dumbbell Shaped Water',
    value: 42,
    left: 84,
    top: 31.5,
    direction: false,
  },
];

export const locations: ILocation[] = [
  ...numberedLocations,
  ...restLocations,
  ...washroomLocations,
  ...drinkingWater,
  ...parking,
  ...buggyStand,
  {
    name: 'Gift Shop',
    value: '/amenities/gift.svg',
    left: 53,
    top: 71,
    color: '#FFB93E',
    direction: false,
  },
  {
    name: 'Play Area',
    value: '/amenities/play.svg',
    left: 14,
    top: 84,
    color: '#DD790A',
    direction: true,
  },
  {
    name: 'Feeding Room',
    value: '/amenities/feeding.svg',
    left: 17.5,
    top: 84,
    color: '#D10096',
    direction: false,
  },
  {
    name: 'Food',
    value: '/amenities/restaurant.svg',
    left: 36.5,
    top: 76.5,
    color: '#D35D0F',
    direction: false,
  },
  {
    name: 'Cafe',
    value: '/amenities/food.svg',
    left: 40.75,
    top: 76.7,
    color: '#DD790A',
    direction: false,
  },
  {
    name: 'Guide',
    value: '/amenities/guide.svg',
    left: 62.75,
    top: 82,
    color: '#A0B165',
    direction: false,
  },
  {
    name: 'Ticket Counter',
    value: '/amenities/ticket.svg',
    left: 59.25,
    top: 82,
    color: '#854C12',
    direction: true,
  },
];
