import type { Metadata } from 'next';
import { Braah_One, Merriweather, Merriweather_Sans } from 'next/font/google';

import Navbar from '@/components/common/Navbar';
import SplashScreen from '@/components/common/SpashScreen';
import Footer from '@/components/Footer/Footer';

import './globals.css';

const merriweather = Merriweather({
  subsets: ['latin'],
  variable: '--font-merriweather',
  weight: ['400', '700', '900'],
});

const merriweatherSans = Merriweather_Sans({
  subsets: ['latin'],
  variable: '--font-merriweather-sans',
  weight: ['400'],
});

const braahOne = Braah_One({
  subsets: ['latin'],
  variable: '--font-braah-one',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${merriweatherSans.variable} ${braahOne.variable} bg-primary min-w-screen overflow-x-clip antialiased`}
      >
        <SplashScreen />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
