import type { Metadata } from 'next';
import { ChakraProvider } from '@chakra-ui/react';
import { Merriweather, Merriweather_Sans } from 'next/font/google';
import './globals.css';

const merriweather = Merriweather({
  subsets: ['latin'],
  variable: '--font-merriweather',
  weight: ['400', '700', '900'],
});

const merriweatherSans = Merriweather_Sans({
  subsets: ['latin'],
  variable: '--font-merriweather-sans',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ChakraProvider>
        <body
          className={`${merriweather.variable} ${merriweatherSans.variable} antialiased`}
        >
          {children}
        </body>
      </ChakraProvider>
    </html>
  );
}
